apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bee-web.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.config.fileName }}: |
    {
      "port": {{ .Values.container.port }},
      "host": {{ .Values.config.host | quote }},
      "nats": {{ toJson .Values.config.nats }},
      "routes": {{ toJson .Values.config.routes }},
      "cors": {{ toJson .Values.config.cors }},
      "auth": {{ toJson .Values.config.auth }},
      "history": {
        "baseUrl": {{ .Values.config.history.baseUrl | quote }},
        "defaultLimit": {{ .Values.config.history.defaultLimit }}
      }
    }
